import turtle
wn = turtle.Screen()             
wn.bgcolor("blue")


tess = turtle.Turtle()           
tess.color("orange")
tess.pensize(7)

alex = turtle.Turtle()           
alex.color("gray")
alex.pensize(3)

tess.forward(70)                 
tess.left(90)
tess.forward(30)
tess.right(90)
tess.forward(90)
tess.left(70)                   
tess.forward(50)
tess.left(110)
tess.forward(105)



tess.right(90)                 
tess.forward(30)                
tess.left(90)
tess.forward(70)
tess.left(90)
tess.forward(30)
tess.right(90)
tess.forward(85)
tess.left(70)
tess.forward(50)
tess.left(110)
tess.forward(105)
tess.right(90)
tess.forward(30) 


alex.forward(70)                 
alex.left(90)
alex.forward(30)
alex.right(90)
alex.forward(90)
alex.left(70)                   
alex.forward(50)
alex.left(110)
alex.forward(105)

alex.right(90)                  
alex.forward(30)                
alex.left(90)
alex.forward(70)
alex.left(90)
alex.forward(30)
alex.right(90)
alex.forward(85)
alex.left(70)
alex.forward(50)
alex.left(110)
alex.forward(105)
alex.right(90)
alex.forward(30)

wn.exitonclick()
